
JWT_SECRET: "JayeshSampleTestJWT"
server:
  port: 9091

spring:
  application:
    name: USER-SERVICE
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true


  datasource:
    url: jdbc:mysql://localhost:3306/anishare
    username: springUser
    password: springUser@123
    driver-class-name: com.mysql.cj.jdbc.Driver





eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost